name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt-get install -f libxcb-composite0-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Set Version Env Variable
      run : "export PACKAGE_VER=cargo pkgid | cut -d# -f2 | cut -d: -f2"
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      uses: actions/upload-artifact@v2.1.3
      with:
        # Artifact name
        name: emojis-${{ env.PACKAGE_VER }}--ubuntu
        # A file, directory or wildcard pattern that describes what to upload
        path:  ./target/release/emojis
        # The desired behavior if no files are found using the provided path.
  windows-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Chocolatey
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - name: Install Rustup
      run: choco install rust
    - name: Build
      run: cargo build --release --verbose
    - name: Set Version Env Variable
      run : "$env:PACKAGE_VER = cargo pkgid | cut -d# -f2 | cut -d: -f2"
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      uses: actions/upload-artifact@v2.1.3
      with:
        # Artifact name
        name: emojis-${{ env.PACKAGE_VER }}--windows
        # A file, directory or wildcard pattern that describes what to upload
        path:  ./target/release/*.exe
        # The desired behavior if no files are found using the provided path.
