name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt-get install -f libxcb-composite0-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      uses: actions/upload-artifact@v2.1.3
      with:
        # Artifact name
        name: emojis.linux
        # A file, directory or wildcard pattern that describes what to upload
        path:  ./target/release/emojis
        # The desired behavior if no files are found using the provided path.
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Test
      run: dir
    - name: Install Chocolatey
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - name: Install Rustup
      run: choco install rust
    - name: Debug Output
      run: tree
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      uses: actions/upload-artifact@v2.1.3
      with:
        # Artifact name
        name: emojis.exe
        # A file, directory or wildcard pattern that describes what to upload
        path:  ./target/release/*.exe
        # The desired behavior if no files are found using the provided path.
